# Generated by Django 4.2.4 on 2023-08-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blue',
            new_name='Aqua',
        ),
    ]
