# Generated by Django 4.2.4 on 2023-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0002_rename_blue_aqua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqua',
            name='app_name',
            field=models.CharField(max_length=50, verbose_name='app name'),
        ),
    ]
